bundled-resources:
  base-path: /dev/pschmalz/wave_function_collapse
  allowed-name-suffixes: png
file-system:
  temp-dir-prefix: wave_function_collapse
view:
  images-grid:
    distance-between: 20
    distance-edge: 10
    size: 30
    background: 255
    width: 300
    height: 300
    upper-left:
      x: 100
      y: 0